spring.application.name=clinic
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
server.port=8081


#spring.liquibase.change-log=classpath:changelog/db.changelog-master.xml
#spring.liquibase.url=jdbc:mysql://localhost:3306/clinic?serverTimeZone=UTC
#spring.liquibase.user=clinic
#spring.liquibase.password=lingdon
#spring.liquibase.enabled=false
#clinic-secret=clinic-secret